### PR TITLE
Corrects defaults for redhat 5

### PR DESCRIPTION
**Pull request by traylenator**
Currently when run on centos 5 system 

```
<root@vb-slc5-next-01> /usr/local/bin/mlocate.cron:

updatedb:/etc/updatedb.conf:3: unknown variable `PRUNE_BIND_MOUNTS'
updatedb:/etc/updatedb.conf:5: unknown variable `PRUNENAMES'
```

mlocate is version 0.15.

### CODE REVIEW

**Comment by traylenator** [comment]
Tests are failing but am pretty sure they will anyway on 

```
manifests/cron.pp - WARNING: top-scope variable being used without an explicit namespace on line 7
manifests/install.pp - WARNING: top-scope variable being used without an explicit namespace on line 8
manifests/install.pp - WARNING: top-scope variable being used without an explicit namespace on line 9
```

**Comment by traylenator** [comment]
Will rebase once PR #2  is resolved somehow.

**Comment by adamcrews** [comment]
PR #2 was merged, but this didn't need a rebase to merge cleanly.  Thanks for the PR's.  I'll get a new forge release out shortly.

**Comment by adamcrews** [comment]
v0.2.0 has been pushed to the forge.  Thanks for the contributions!

**Pull request merged**
